[package]
name = "warp-openssl"
version = "0.5.4"
edition = "2021"
description = "OpenSSL bindings for Warp TLS server"
license = "MIT"
authors = [
    "Sandeep Bansal <sandeep.bansal85@gmail.com>",
    "René Rössler <rene@freshx.de>",
]
readme = "README.md"
documentation = "https://docs.rs/warp-openssl"
repository = "https://github.com/Azure/warp-openssl"
categories = ["web-programming::http-server"]
keywords = ["warp", "openssl", "tls", "https"]
autotests = true


[features]
openssl-vendored = ["openssl/vendored"]

[dependencies]
tokio-openssl = "0.6"
openssl = { version = "0.10" }
tokio = { version = "1", features = ["net", "macros"] }
tracing = "0.1"
futures-util = "0.3"
warp = { version = "0.4", default-features = false }
hyper = { version = "1", features = ["server", "http1", "http2"] }
hyper-util = { version = "0.1", features = ["server-auto", "server-graceful", "tokio", "service"] }
http = "1"
tower-service = "0.3"

[dev-dependencies]
reqwest = { version = "0.13", features = ["rustls", "native-tls"] }
rstest = "0.26"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
env_logger = "*"

[[test]]
name = "server"
path = "tests/server.rs"
